name: RemotePad
options:
  bundleIdPrefix: com.eunhhu
  deploymentTarget:
    iOS: "17.0"
targets:
  RemotePad:
    type: application
    platform: iOS
    sources:
      - Sources
      - path: ../RemotePadClient/Sources/RemotePadClient
        group: RemotePadClient
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.eunhhu.remotepad
        DEVELOPMENT_TEAM: FGS77772YC
        CODE_SIGN_STYLE: Automatic
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator
        MARKETING_VERSION: 0.2.2
        CURRENT_PROJECT_VERSION: 3
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: RemotePad
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
schemes:
  RemotePad:
    build:
      targets:
        RemotePad: all
    run:
      config: Debug
    archive:
      config: Release
