use crate::protocol::KeyCode;

pub const WINDOWS_EXTENDED_SCAN_FLAG: u16 = 0xFF00;

pub fn windows_scan_code_for_dom_code(code: &str) -> Option<KeyCode> {
    let scan = match code {
        "KeyA" => 0x1E,
        "KeyB" => 0x30,
        "KeyC" => 0x2E,
        "KeyD" => 0x20,
        "KeyE" => 0x12,
        "KeyF" => 0x21,
        "KeyG" => 0x22,
        "KeyH" => 0x23,
        "KeyI" => 0x17,
        "KeyJ" => 0x24,
        "KeyK" => 0x25,
        "KeyL" => 0x26,
        "KeyM" => 0x32,
        "KeyN" => 0x31,
        "KeyO" => 0x18,
        "KeyP" => 0x19,
        "KeyQ" => 0x10,
        "KeyR" => 0x13,
        "KeyS" => 0x1F,
        "KeyT" => 0x14,
        "KeyU" => 0x16,
        "KeyV" => 0x2F,
        "KeyW" => 0x11,
        "KeyX" => 0x2D,
        "KeyY" => 0x15,
        "KeyZ" => 0x2C,
        "Digit0" => 0x0B,
        "Digit1" => 0x02,
        "Digit2" => 0x03,
        "Digit3" => 0x04,
        "Digit4" => 0x05,
        "Digit5" => 0x06,
        "Digit6" => 0x07,
        "Digit7" => 0x08,
        "Digit8" => 0x09,
        "Digit9" => 0x0A,
        "Space" => 0x39,
        "Enter" => 0x1C,
        "Escape" => 0x01,
        "Backspace" => 0x0E,
        "Tab" => 0x0F,
        "ShiftLeft" => 0x2A,
        "ShiftRight" => 0x36,
        "ControlLeft" => 0x1D,
        "ControlRight" => WINDOWS_EXTENDED_SCAN_FLAG | 0x1D,
        "AltLeft" => 0x38,
        "AltRight" => WINDOWS_EXTENDED_SCAN_FLAG | 0x38,
        "ArrowUp" => WINDOWS_EXTENDED_SCAN_FLAG | 0x48,
        "ArrowLeft" => WINDOWS_EXTENDED_SCAN_FLAG | 0x4B,
        "ArrowRight" => WINDOWS_EXTENDED_SCAN_FLAG | 0x4D,
        "ArrowDown" => WINDOWS_EXTENDED_SCAN_FLAG | 0x50,
        _ => return None,
    };
    KeyCode::from_wire(scan)
}

pub const QA_KEY_FIXTURE: &[&str] = &[
    "KeyZ",
    "KeyX",
    "KeyC",
    "KeyA",
    "KeyS",
    "KeyD",
    "KeyQ",
    "KeyW",
    "KeyE",
    "KeyR",
    "KeyT",
    "KeyY",
    "Digit1",
    "Digit2",
    "Digit3",
    "Digit4",
    "Digit5",
    "Digit6",
    "Space",
    "Enter",
    "ArrowUp",
    "ArrowLeft",
    "ArrowRight",
    "ArrowDown",
];
